### ISSUE TITLE
GPT/B-01 - Implementierung von Benutzerkonten im Backend

### ISSUE THREAD

**Issue by Spoastenkoasten** [lbocker/GrammatikTestTiedemann#18]
Die Benutzer unseres Grammatikportals sollen sich anmelden können, um Fortschritte und Punkte speichern zu können. So kann man speichern, was von einem Nutzer schon an Aufgaben bearbeitet wurde und wo noch verbesserungsbedarf ansteht. 
Wir brauchen eine Adminrolle zum einpflegen von Kursen und Tasks.

**Erste Implementierung:**
- username
- password
- role (admin or user)
- score
- Completed Tasks

Die completed Task wird eine Verbindung zu einer weiteren Entität, die speichert, welche Kurse wie gut von dem Benutzer bearbeitet wurden. Diese wird wie folgt aussehen.

- [ ] Ticket anlegen für die Completed Task
- [ ] Service Methode zur Berechnung des Scores

**Comment by hasanmohsen1** [comment]
Nicht wirklich ein Issue, sondern ein Feature Task. Kannst du schließen oder hier lassen, aber bitte auch im Miro Board hinterlegen, sodass der Lehrer nachsehen kann wer was gemacht hat ;) 

@ShamonAureliusRex bei der Bearbeitung beachten, dass wir ein getrenntes System haben. Daher ist es wichtig, eine User API zu erstellen, für die Kommunikation zwischen dem Client und dem Server und um die Daten entsprechend hin- und herzuschicken. Ob du JWT oder Auth0, oder was auch immer verwendest ist dir überlassen. 
Aber hier mal eine (alte) Dokumentation mit JWT: https://liujijieseason.medium.com/angular-symfony-jwt-authentication-5fd39da2a1ac

**Comment by hasanmohsen1** [comment]
https://github.com/lbocker/GrammatikTestTiedemann/pull/22
