### ISSUE TITLE
GPT/B-02 - Create Task and Course Infrastructure

### ISSUE THREAD

**Issue by Spoastenkoasten** [lbocker/GrammatikTestTiedemann#19]
Hier geht es um die Kernfunktioalität unseres Projekts

**Course**
- name
- description
- Tasks

**Task**

- name
- type: string with STATIC_NAMES
- Right: string
- Wrong: string
- DragDropGroups: DragDrop[]

(siehe weitere Anforderung im Bild)

![image](https://github.com/lbocker/GrammatikTestTiedemann/assets/89301739/87622e07-57f1-4195-8be7-c475625bf5fe)

**Comment by hasanmohsen1** [comment]
@Spoastenkoasten die Kernfunktionalität der API ist bereits vorhanden:

![image](https://github.com/lbocker/GrammatikTestTiedemann/assets/110456953/87730d94-f41d-41d1-94e3-674d3ea9a8cd)

Wieso ist das ein Issue?

**Comment by hasanmohsen1** [comment]
DIe API wurde überarbeitet, eine Doku folgt.
